# @package experiment.config.monty_config.motor_system_config.policy_selector.policy

_target_: tbp.monty.simulators.arc_agi.ArcRegionScanPolicy
agent_id: agent_id_0
sensor_id: patch_0
frame_sensor_id: view_finder
region_index: 0
recognition_passes: 2
