# @package experiment.config.monty_config.motor_system_config.policy_selector.policy

_target_: tbp.monty.frameworks.models.salience.motor_policy.LookAtGoal
agent_id: agent_id_0
sensor_id: view_finder
