# @package experiment.config.monty_config.motor_system_config.policy_selector.policy

_target_: tbp.monty.frameworks.models.motor_policies.SnakeScanPolicy
agent_id: agent_id_0
sensor_id: patch_0
frame_size: null
patch_size: 1
stride: 1
