# This file may be used to create an environment using:
#
# ## Miniconda
#     $ conda env create --file environment_arm64.yml --subdir=osx-64
# If you are using the zsh shell, run:
#     $ conda init zsh
# Or, if you are using a different shell, run:
#     $ conda init
# After init, if you do not want conda to change your global shell when
# you open a new terminal, run:
#     $ conda config --set auto_activate_base false
# Finally, activate the environment with:
#     $ conda activate tbp.monty
#     $ conda config --env --set subdir osx-64
#
# ## Anaconda (omit --subdir=osx-64)
#     $ conda env create --file environment_arm64.yml
# If you are using the zsh shell, run:
#     $ conda init zsh
# Or, if you are using a different shell, run:
#     $ conda init
# After init, if you do not want conda to change your global shell when
# you open a new terminal, run:
#     $ conda config --set auto_activate_base false
# Finally, activate the environment with:
#     $ conda activate tbp.monty
#
# platform: osx-arm64
name: tbp.monty
channels:
  - aihabitat
  - pytorch
  - pyg
  - defaults
  - conda-forge

dependencies:
  - python=3.8
  - cmake>=3.14.0
  - pyg::pyg
  - wget

  - aihabitat::habitat-sim=0.2.2
  - mkl<2022 # prevents Intel errors when osx-64 environment is running on osx-arm64 platform
  - pytorch::pytorch=1.11.0
  - conda-forge::quaternion=2023.0.3 # later versions missing np.long
  - pytorch::torchvision
  - aihabitat::withbullet

  - pip
  - pip:
      - -e .[dev]