# This file may be used to create an environment using:
#
# ## Miniconda or Anaconda
#     $ conda env create --file environment.yml
# If you are using the zsh shell, run:
#     $ conda init zsh
# Or, if you are using a different shell, run:
#     $ conda init
# After init, if you do not want conda to change your global shell when
# you open a new terminal, run:
#     $ conda config --set auto_activate_base false
# Finally, activate the environment with:
#     $ conda activate tbp.monty
#
# platform: default
name: tbp.monty
channels:
  - aihabitat
  - pytorch
  - pyg
  - defaults
  - conda-forge

dependencies:
  - python=3.8
  - cmake>=3.14.0
  - pyg::pyg
  - wget

  - aihabitat::habitat-sim=0.2.2
  - pytorch::pytorch=1.11.0
  - conda-forge::quaternion=2023.0.3 # later versions missing np.long
  - pytorch::torchvision
  - aihabitat::withbullet

  - pip
  - pip:
      - -e .[dev]

