# This file may be used to create an environment using:
#
# ## Miniconda or Anaconda
#     $ conda env create --file environment.yml
# If you are using the zsh shell, run:
#     $ conda init zsh
# Or, if you are using a different shell, run:
#     $ conda init
# After init, if you do not want conda to change your global shell when
# you open a new terminal, run:
#     $ conda config --set auto_activate_base false
# Finally, activate the environment with:
#     $ conda activate tbp.monty
#
# platform: default
name: tbp.monty
channels:
  - aihabitat
  - pyg
  - conda-forge
  - defaults

dependencies:
  - python=3.9

  - aihabitat::habitat-sim
  - aihabitat::withbullet
  - conda-forge::cmake>=3.14.0
  - conda-forge::importlib_resources
  - conda-forge::matplotlib
  - conda-forge::mkl<2022
  - conda-forge::numpy
  - conda-forge::pandas
  - conda-forge::pillow
  - conda-forge::quaternion
  - conda-forge::scikit-image
  - conda-forge::scikit-learn
  - conda-forge::scipy
  - conda-forge::sympy
  - conda-forge::tqdm
  - conda-forge::wandb
  - conda-forge::wget
  - pyg::pyg

  - pip
  - pip:
      - -e .[dev]
      - torch
      - torchvision

