name: "Should Run Monty"
description: "Determines if the Monty workflow should run based on the changed files."

inputs:
  working_directory:
    description: "The directory to run the command in."
    required: true

outputs:
  should_run_monty:
    description: "Whether the Monty workflow should run."
    value: ${{ steps.should_run.outputs.should_run_monty }}

runs:
  using: "composite"
  steps:
    - name: Filter by path for a pull request
      if: ${{ github.event_name == 'pull_request' }}
      id: filter_by_path_pr
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
          git diff --name-only origin/${{ github.base_ref }} > changed_files.txt
          while IFS= read -r changed_file
          do
            echo $changed_file
            if [[ $changed_file != .github/ISSUE_TEMPLATE/* ]] &&
               [[ $changed_file != .vscode/* ]] &&
               [[ $changed_file != docs/* ]] &&
               [[ $changed_file != rfcs/* ]] &&
               [[ $changed_file != tools/* ]] &&
               [[ $changed_file != CODE_OF_CONDUCT.md ]] &&
               [[ $changed_file != CONTRIBUTING.md ]] &&
               [[ $changed_file != LICENSE ]] &&
               [[ $changed_file != MAINTAINERS.md ]] &&
               [[ $changed_file != README.md ]]; then
              echo "should_run_monty=true" >> $GITHUB_OUTPUT
              exit 0
            fi
          done < changed_files.txt
    - name: Filter by path for a push
      if: ${{ github.event_name == 'push' }}
      id: filter_by_path_push
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
        git diff --name-only HEAD^1 > changed_files.txt
        while IFS= read -r changed_file
        do
          echo $changed_file
          if [[ $changed_file != .github/ISSUE_TEMPLATE/* ]] &&
              [[ $changed_file != .vscode/* ]] &&
              [[ $changed_file != docs/* ]] &&
              [[ $changed_file != rfcs/* ]] &&
              [[ $changed_file != tools/* ]] &&
              [[ $changed_file != CODE_OF_CONDUCT.md ]] &&
              [[ $changed_file != CONTRIBUTING.md ]] &&
              [[ $changed_file != LICENSE ]] &&
              [[ $changed_file != MAINTAINERS.md ]] &&
              [[ $changed_file != README.md ]]; then
            echo "should_run_monty=true" >> $GITHUB_OUTPUT
            exit 0
          fi
        done < changed_files.txt
    - name: Should run
      id: should_run
      if: ${{ steps.filter_by_path_pr.outputs.should_run_monty == 'true' || steps.filter_by_path_push.outputs.should_run_monty == 'true'}}
      shell: bash
      run: echo "should_run_monty=true" >> $GITHUB_OUTPUT
