name: "Should Run Monty"
description: "Determines if the Monty workflow should run based on the changed files."

inputs:
  working_directory:
    description: "The directory to run the command in."
    required: true

outputs:
  should_run_monty:
    description: "Whether the Monty workflow should run."
    value: ${{ steps.should_run.outputs.should_run_monty }}

runs:
  using: "composite"
  steps:
    - name: Filter by path for a pull request
      if: ${{ github.event_name == 'pull_request' }}
      id: filter_by_path_pr
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
        git diff --name-only origin/${{ github.base_ref }} > changed_files.txt
        ./.github/actions/should_run_monty/check_changed_files.sh
    - name: Filter by path for a push
      if: ${{ github.event_name == 'push' }}
      id: filter_by_path_push
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: |
        git diff --name-only HEAD^1 > changed_files.txt
        ./.github/actions/should_run_monty/check_changed_files.sh
    - name: Should run
      id: should_run
      if: ${{ steps.filter_by_path_pr.outputs.should_run_monty == 'true' || steps.filter_by_path_push.outputs.should_run_monty == 'true'}}
      shell: bash
      run: echo "should_run_monty=true" >> $GITHUB_OUTPUT
