# @package config.env_interface_args.object_init_sampler
# Predefined rotations sampler - uses 3 rotations (subset for 77obj benchmarks)

_target_: tbp.monty.frameworks.environments.object_init_samplers.Predefined
rotations: ${vars.rotations_3}
