# Copyright 2026 Thousand Brains Project
#
# Copyright may exist in Contributors' modifications
# and/or contributions to the work.
#
# Use of this source code is governed by the MIT
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

from __future__ import annotations

from pathlib import Path  # noqa: TC003
from typing import ClassVar, Dict, Mapping, Sequence, Type

import numpy as np
import wandb
from sklearn.preprocessing import LabelEncoder

from tbp.monty.frameworks import telemetry
from tbp.monty.frameworks.experiments import monty_experiment
from tbp.monty.frameworks.experiments.mode import ExperimentMode
from tbp.monty.frameworks.loggers.monty_handlers import MontyHandler
from tbp.monty.frameworks.models import graph_matching
from tbp.monty.frameworks.models.monty_base import MontyBase
from tbp.monty.frameworks.telemetry.episode.schemas import (
    EpisodeStatsTelemetry,
    LearningModuleObjectRecognized,
    LearningModuleStateTelemetry,
    LMTelemetryEvent,
)
from tbp.monty.frameworks.telemetry.episode.stats import GraphLMStats
from tbp.monty.frameworks.telemetry.schemas import TelemetrySchema
from tbp.monty.frameworks.telemetry.subscribers import TelemetrySubscriber
from tbp.monty.frameworks.utils.logging_utils import target_data_to_dict

_LMEventCache = Dict[str, Dict[Type[LMTelemetryEvent], LMTelemetryEvent]]
"""Custom type to store the last received event per type for each LM during the episode.
Structure::
    {lm_name: {type: event, ...}, ...}  # lm_name typically starts with "LM_"
"""


def _blank_overall_stats() -> dict:
    """Returns zeroed accumulators for overall train/eval stats."""
    return dict(
        num_episodes=0,
        num_correct=0,
        num_correct_mlh=0,
        num_no_match=0,
        num_confused=0,
        num_confused_mlh=0,
        num_pose_time_out=0,
        num_time_out=0,
        num_patch_off_object=0,
        num_no_label=0,
        num_consistent_child_obj=0,
        num_correct_child_or_parent=0,
        num_correct_per_lm=0,
        num_correct_mlh_per_lm=0,
        num_consistent_child_obj_per_lm=0,
        num_no_match_per_lm=0,
        num_confused_per_lm=0,
        num_confused_mlh_per_lm=0,
        num_pose_time_out_per_lm=0,
        num_time_out_per_lm=0,
        num_patch_off_object_per_lm=0,
        num_no_label_per_lm=0,
        episode_correct=0,
        episode_correct_mlh=0,
        episode_no_match=0,
        episode_confused=0,
        episode_confused_mlh=0,
        episode_pose_time_out=0,
        episode_time_out=0,
        episode_avg_prediction_error=[],
        episode_lm_performances=[],
        # Total number of steps performed during the episode,
        # including steps where no sensory data was passed to the learning-modules:
        monty_steps=[],
        # Number of global monty *matching* steps. Counts steps when at least one LM
        # was updated:
        monty_matching_steps=[],
        # Number of steps associated with an individual LM processing data, i.e.
        # can differ across the LMs of a Monty model:
        episode_lm_steps=[],
        episode_lm_steps_indv_ts=[],
        episode_symmetry_evidence=[],
        rotation_errors=[],
        run_times=[],
        # Policy stats
        goal_states_attempted=0,
        goal_state_success_rate=0,
    )


# TODO telemetry: maybe move this into stats.py or elsewhere?
class BasicGraphLMStatsMixin:
    """Accumulates and formats train/eval stats for graph LMs across episodes.

    Replaces the aggregation logic of `BasicGraphMatchingLogger`.
    """

    # Instantiated by the implementing class
    received_lm_events: _LMEventCache

    # Session stats ClassVars similar to LOGGING_REGISTRY mechanic
    overall_train_stats: ClassVar[dict] = _blank_overall_stats()
    overall_eval_stats: ClassVar[dict] = _blank_overall_stats()

    def __init__(self, **kwargs):
        """Initializes stats-related variables."""
        super().__init__(**kwargs)

        self.data = self._blank_data()
        """Stores stats generated by `update_episode_data`."""

        # Order of performance_options matters since we check them in sequence for each
        # lm. The lower in the list, the stronger it is to determine overall
        # performance. Performance lower down in the list will always trump higher-up
        # performance values. For example, if we have N LMs and one of them has
        # performance "correct", the overall episode performance is correct. It doesn't
        # matter if all the other LMs have a time_out performance.
        # The three strong terminal condition cases (no_match, confused, correct) need
        # to be listed last. The weaker time out conditions first so they don't
        # overwrite the performance of an LM that caused the episode to end.
        # TODO: what if 2 LMs reach a strong terminal state at the same step? For
        # example if one LM reaches the correct state and the other confused the
        # performance will be logged as correct. However, in this case we would
        # probably want to keep moving or log a conflicting performance.
        # TODO: If we have a time out and look at the mlh, we should take the majority
        # vote and not let correct_mlh win
        self.performance_options = [
            "patch_off_object",
            "no_label",
            "pose_time_out",
            "time_out",
            "consistent_child_obj",  # also counted if LM didn't converge
            "confused_mlh",
            "correct_mlh",
            "no_match",
            "confused",
            "correct",
        ]
        self.performance_encoder = LabelEncoder()
        self.performance_encoder.fit(self.performance_options)

    @staticmethod
    def _blank_data() -> dict:
        """Returns an empty `self.data` structure for use with `MontyHandler`.

        Preserves the ``BASIC`` / ``DETAILED`` shape previously maintained by
        `BasicGraphMatchingLogger` for handler compatibility.
        """
        return dict(
            BASIC=dict(
                train_stats={},
                train_overall_stats={},
                train_targets={},
                train_actions={},
                train_timing={},
                eval_stats={},
                eval_overall_stats={},
                eval_actions={},
                eval_targets={},
                eval_timing={},
            ),
            DETAILED={},
        )

    def get_stats_per_lm(
        self,
        model: MontyBase,
        target: Mapping,
        target_data: Mapping,
        episode_seed: int,
    ) -> dict:
        """Outer-half equivalent of `logging_utils.get_stats_per_lm`.

        Returns:
            Performance stats of all learning modules.

        Raises:
            TypeError: If an invalid `LearningModuleStateTelemetry` was received.
        """
        performance_dict = {}

        for lm_name, lm_schemas in self.received_lm_events.items():
            lm_state = lm_schemas.get(LearningModuleStateTelemetry)
            if not isinstance(lm_state, LearningModuleStateTelemetry):
                raise TypeError(f"Invalid LearningModuleStateTelemetry for '{lm_name}'")

            lm_perf_dict = GraphLMStats.get_lm_performance_stats(
                lm=lm_state,
                model=model,
                target=target,
                target_data=target_data,
                episode_seed=episode_seed,
            )
            performance_dict[lm_name] = lm_perf_dict

        return performance_dict

    def update_episode_data(self, logger_args: dict, model: MontyBase):
        """Equivalent of `BasicGraphMatchingLogger.update_episode_data`."""
        target: Mapping | None = logger_args.get("target")
        target_data: Mapping | None = target_data_to_dict(target) if target else None

        performance_dict = self.get_stats_per_lm(
            model=model,
            target=target,
            target_data=target_data,
            episode_seed=logger_args["episode_seed"],
        )

        mode = model.experiment_mode
        episode = logger_args[f"{mode}_episodes"]
        actions = model.motor_system.action_sequence
        logger_time = {k: v for k, v in logger_args.items() if k != "target"}
        self.data["BASIC"][f"{mode}_stats"][episode] = performance_dict

        self.update_overall_stats(
            mode=mode,
            episode=episode,
            episode_steps=model.episode_steps,
            monty_matching_steps=model.matching_steps,
        )
        overall_stats = self.get_formatted_overall_stats(mode, episode)

        self.data["BASIC"][f"{mode}_overall_stats"][episode] = overall_stats
        self.data["BASIC"][f"{mode}_actions"][episode] = actions
        self.data["BASIC"][f"{mode}_targets"][episode] = target_data
        self.data["BASIC"][f"{mode}_timing"][episode] = logger_time
        self.data["BASIC"][f"{mode}_stats"][episode]["target"] = target_data

    def update_overall_stats(
        self,
        mode: ExperimentMode,
        episode: int,
        episode_steps: int,
        monty_matching_steps: int,
    ):
        """Accumulates per-episode stats into the running overall stats dict.

        Mirrors `BasicGraphMatchingLogger.update_overall_stats`.
        """
        if mode is ExperimentMode.TRAIN:
            stats = self.overall_train_stats
        else:
            stats = self.overall_eval_stats

        lm_performances = []
        for lm_name in self.received_lm_events:
            # This accumulates stats from all LM
            episode_stats = self.data["BASIC"][f"{mode}_stats"][episode][lm_name]
            performance = episode_stats["primary_performance"]

            if performance is not None:  # in pre training, performance is None
                stats[f"num_{performance}_per_lm"] += 1
                lm_performances.append(performance)

            stats["rotation_errors"].append(episode_stats["rotation_error"])
            stats["run_times"].append(episode_stats["time"])
            stats["episode_lm_steps"].append(episode_stats["num_steps"])
            stats["episode_lm_steps_indv_ts"].append(
                episode_stats["individual_ts_reached_at_step"]
            )
            stats["episode_symmetry_evidence"].append(
                episode_stats["symmetry_evidence"]
            )
            stats["monty_steps"].append(episode_steps)
            stats["monty_matching_steps"].append(monty_matching_steps)
            # older LMs don't have prediction error stats

            if "episode_avg_prediction_error" in episode_stats:
                stats["episode_avg_prediction_error"].append(
                    episode_stats["episode_avg_prediction_error"]
                )

            if performance in {"consistent_child_obj", "correct", "correct_mlh"}:
                stats["num_correct_child_or_parent"] += 1

            stats["goal_states_attempted"] = episode_stats["goal_states_attempted"]

            stats["goal_state_success_rate"] = (
                episode_stats["goal_state_achieved"]
                / episode_stats["goal_states_attempted"]
                if episode_stats["goal_states_attempted"]
                else 0  # Handles division by 0
            )

        episode_performance = None
        stats["episode_lm_performances"].append(lm_performances)
        for p in self.performance_options:
            if p in lm_performances:
                # order of performance_options matters since we overwrite here!
                # episode_performance is only no_match if no lm had another
                # performance. That makes it possible for some lms to have no match
                # but still have an overall performance of correct (or other).
                episode_performance = p

        if episode_performance:
            for p in self.performance_options:
                stats[f"episode_{p}"] = int(p == episode_performance)
                stats[f"num_{p}"] += int(p == episode_performance)

        stats["num_episodes"] += 1

    def get_formatted_overall_stats(self, mode: ExperimentMode, episode: int) -> dict:
        """Formats the running overall stats into a flat dict for Monty handlers.

        Equivalent of `BasicGraphMatchingLogger.get_formatted_overall_stats`.

        Returns:
            A dict of stats suitable to pass directly to ``MontyHandler``, e.g. Wandb.
        """
        if mode is ExperimentMode.TRAIN:
            stats = self.overall_train_stats
        else:
            stats = self.overall_eval_stats

        lm_count = len(self.received_lm_events)

        # Stores rotation errors if the object was recognized ("correct")
        correct_rotation_errors = [
            re for re in stats["rotation_errors"] if re is not None
        ]
        episode_re = [
            re for re in stats["rotation_errors"][-lm_count:] if re is not None
        ]
        episode_individual_ts_steps = [
            steps
            for steps in stats["episode_lm_steps_indv_ts"][-lm_count:]
            if steps is not None
        ]
        episode_lm_performances = self.performance_encoder.transform(
            stats["episode_lm_performances"][-1]
        )

        if len(episode_re) == 0:  # object was not recognized
            episode_re = [-1]

        overall_stats = {
            # % for performance per episode. This is the overall performance
            # of a Monty model, individual LMs may have different performances.
            # _mlh performances are determined using the most likely hypothesis
            # after a time out. For instance correct_mlh means that max steps
            # was reached without being confident enough about one object and pose
            # to classify it but the hypothesis with the highest evidence was
            # correct.
            "overall/percent_correct": (
                (stats["num_correct"] + stats["num_correct_mlh"])
                / (stats["num_episodes"])
            )
            * 100,
            "overall/percent_no_match": (
                stats["num_no_match"] / (stats["num_episodes"])
            )
            * 100,
            "overall/percent_confused": (
                (stats["num_confused"] + stats["num_confused_mlh"])
                / (stats["num_episodes"])
            )
            * 100,
            "overall/percent_correct_mlh": (
                (stats["num_correct_mlh"]) / (stats["num_episodes"])
            )
            * 100,
            "overall/percent_confused_mlh": (
                (stats["num_confused_mlh"]) / (stats["num_episodes"])
            )
            * 100,
            "overall/percent_pose_time_out": (
                stats["num_pose_time_out"] / (stats["num_episodes"])
            )
            * 100,
            "overall/percent_time_out": (
                stats["num_time_out"] / (stats["num_episodes"])
            )
            * 100,
            "overall/percent_used_mlh_after_timeout": (
                (stats["num_correct_mlh"] + stats["num_confused_mlh"])
                / (stats["num_episodes"])
            )
            * 100,
            # Mean rotation error on all LMs that recognized the object
            "overall/avg_rotation_error": (
                np.mean(correct_rotation_errors)
                if len(correct_rotation_errors) > 0
                else np.nan
            ),
            "overall/avg_num_lm_steps": (
                np.mean(stats["episode_lm_steps"])
                if len(stats["episode_lm_steps"]) > 0
                else np.nan
            ),
            "overall/avg_num_monty_steps": (
                np.mean(stats["monty_steps"])
                if len(stats["monty_steps"]) > 0
                else np.nan
            ),
            "overall/avg_num_monty_matching_steps": (
                np.mean(stats["monty_matching_steps"])
                if len(stats["monty_matching_steps"]) > 0
                else np.nan
            ),
            "overall/avg_prediction_error": (
                np.mean(stats["episode_avg_prediction_error"])
                if len(stats["episode_avg_prediction_error"]) > 0
                else np.nan
            ),
            "overall/percent_consistent_child_obj": (
                stats["num_consistent_child_obj"] / (stats["num_episodes"])
            )
            * 100,
            "overall/percent_correct_child_or_parent": (
                stats["num_correct_child_or_parent"]
                / (stats["num_episodes"] * lm_count)
            )
            * 100,
            "overall/run_time": np.sum(stats["run_times"]) / lm_count,
            # NOTE: does not take into account different runtimes with multiple LMs
            "overall/avg_episode_run_time": (
                np.mean(stats["run_times"]) if len(stats["run_times"]) > 0 else np.nan
            ),
            "overall/num_episodes": stats["num_episodes"],
            # Stats for most recent episode
            # Performance of the overall Monty model
            "episode/correct": stats["episode_correct"] or stats["episode_correct_mlh"],
            "episode/no_match": stats["episode_no_match"],
            "episode/confused": (
                stats["episode_confused"] or stats["episode_confused_mlh"]
            ),
            "episode/correct_mlh": stats["episode_correct_mlh"],
            "episode/confused_mlh": stats["episode_confused_mlh"],
            "episode/pose_time_out": stats["episode_pose_time_out"],
            "episode/time_out": stats["episode_time_out"],
            "episode/consistent_child_obj": stats["episode_consistent_child_obj"],
            "episode/consistent_child_or_parent": (
                stats["episode_consistent_child_obj"]
                or stats["episode_correct"]
                or stats["episode_correct_mlh"]
            ),
            "episode/used_mlh_after_time_out": stats["episode_correct_mlh"]
            or stats["episode_confused_mlh"],
            "episode/rotation_error": (
                np.mean(episode_re) if len(episode_re) > 0 else np.nan
            ),
            # steps is the max number of steps of all LMs. Some LMs may have taken
            # less steps because they were not on the object all the time.
            "episode/lm_steps": np.max(stats["episode_lm_steps"][-lm_count:]),
            "episode/monty_steps": stats["monty_steps"][-1],
            "episode/monty_matching_steps": stats["monty_matching_steps"][-1],
            "episode/mean_lm_steps_to_indv_ts": (
                np.mean(episode_individual_ts_steps)
                if len(episode_individual_ts_steps) > 0
                else np.nan
            ),
            "episode/run_time": np.max(stats["run_times"][-lm_count:]),
            # Mean symmetry evidence with multiple LMs may be > required evidence
            # since one LM reaching its terminal condition doesn't mean all others do.
            "episode/symmetry_evidence": (
                np.mean(stats["episode_symmetry_evidence"][-lm_count:])
                if len(stats["episode_symmetry_evidence"][-lm_count:]) > 0
                else np.nan
            ),
            "episode/goal_states_attempted": stats["goal_states_attempted"],
            "episode/goal_state_success_rate": stats["goal_state_success_rate"],
            "episode/avg_prediction_error": stats["episode_avg_prediction_error"],
        }

        for p in self.performance_options:
            # % performance for each LM of the Monty model. For instance, some LMs
            # may have no_match but the overall model still recognized the object.
            if p == "correct":
                overall_stats["overall/percent_correct_per_lm"] = (
                    (stats["num_correct_per_lm"] + stats["num_correct_mlh_per_lm"])
                    / (stats["num_episodes"] * lm_count)
                ) * 100
            elif p == "confused":
                overall_stats["overall/percent_confused_per_lm"] = (
                    (stats["num_confused_per_lm"] + stats["num_confused_mlh_per_lm"])
                    / (stats["num_episodes"] * lm_count)
                ) * 100
            elif p in {"correct_mlh", "confused_mlh"}:
                # skip because they are already included in correct and confused stats
                pass
            else:
                overall_stats[f"overall/percent_{p}_per_lm"] = (
                    stats[f"num_{p}_per_lm"] / (stats["num_episodes"] * lm_count)
                ) * 100

        for lm_name in self.received_lm_events:
            lm_stats = self.data["BASIC"][f"{mode}_stats"][episode][lm_name]
            overall_stats[f"{lm_name}/episode/steps_to_individual_ts"] = lm_stats[
                "individual_ts_reached_at_step"
            ]
            overall_stats[f"{lm_name}/episode/individual_ts_rotation_error"] = lm_stats[
                "individual_ts_rotation_error"
            ]
            if "episode_avg_prediction_error" in lm_stats:
                overall_stats[f"{lm_name}/episode/avg_prediction_error"] = lm_stats[
                    "episode_avg_prediction_error"
                ]

        if lm_count > 1:  # add histograms when running multiple LMs
            overall_stats["episode/rotation_error_per_lm"] = wandb.Histogram(episode_re)
            overall_stats["episode/steps_per_lm"] = wandb.Histogram(
                stats["episode_lm_steps"][-lm_count:]
            )
            overall_stats["episode/steps_per_lm_indv_ts"] = wandb.Histogram(
                episode_individual_ts_steps
            )
            overall_stats["episode/symmetry_evidence_per_lm"] = wandb.Histogram(
                stats["episode_symmetry_evidence"][-lm_count:]
            )
            overall_stats["episode/lm_performances"] = wandb.Histogram(
                episode_lm_performances
            )
            # filter out prediction errors that are nan
            prediction_errors = stats["episode_avg_prediction_error"][-lm_count:]
            valid_prediction_errors = [e for e in prediction_errors if not np.isnan(e)]
            if valid_prediction_errors:
                overall_stats["episode/avg_prediction_error_dist"] = wandb.Histogram(
                    valid_prediction_errors
                )
                overall_stats["episode/avg_prediction_error"] = np.mean(
                    valid_prediction_errors
                )

        return overall_stats


class EpisodeTelemetryHandler(BasicGraphLMStatsMixin, TelemetrySubscriber):
    """Aggregates episode telemetry and forwards the results to downstream subscribers.

    Replaces the reporting logic of `BasicGraphMatchingLogger`. The forwarded
    `EpisodeStatsTelemetry` events contain the same `self.data` structure as before.
    """

    @property
    def logger_names(self) -> list[str]:
        """Names of loggers to subscribe to."""
        return [
            f"telemetry.{monty_experiment.__name__}",
            f"telemetry.{graph_matching.__name__}",
        ]

    # TODO telemetry: Hydra log level at module level instead
    def __init__(self, event_level=telemetry.INFO, **kwargs):
        """Initializes the post-episode subscriber.

        Args:
            event_level: Minimum log level for events. Those below this level are
                silently dropped before reaching the handlers. If that logger already
                exists, and `level` is greater than ``telemetry.NOTSET`` (0), the new
                level overrides the old.
            **kwargs: Forwarded to superclass.
        """
        super().__init__(**kwargs)

        self.received_lm_events: _LMEventCache = {}
        """Last received event per type for each LM name during the current episode."""

        self.lm_id_to_name_dict: dict[str, str] = {}
        """Stores the `received_lm_events` LM name associated with an LM ID."""

        self.telemeter = telemetry.getTelemeter(__name__, event_level=event_level)

    def _consume(self, schema: TelemetrySchema):
        """Caches incoming events and updates terminal stats."""
        if isinstance(schema, LMTelemetryEvent):
            lm_name = self.lm_id_to_name_dict.setdefault(
                schema.lm_id, f"LM_{len(self.lm_id_to_name_dict)}"
            )
            self.received_lm_events.setdefault(lm_name, {})[type(schema)] = schema

        if isinstance(schema, LearningModuleObjectRecognized):
            self._update_terminal_stats(schema)

    def _update_terminal_stats(self, event: LearningModuleObjectRecognized):
        """Updates terminal stats associated with object recognition events."""
        # TODO telemetry: running tallies or not?
        # if mode is ExperimentMode.TRAIN:  # TODO: track mode somehow
        #     stats = self.overall_train_stats
        # else:
        #     stats = self.overall_eval_stats
        # if event.terminal_state == TerminalState.MATCH:
        #     stats["episode_correct"] += 1
        #     stats["num_correct"] += 1
        # elif event.terminal_state == TerminalState.NO_MATCH:
        #     stats["episode_no_match"] += 1
        #     stats["num_no_match"] += 1
        pass

    def post_episode(self, logger_args: dict, model: MontyBase):
        """Updates episode stats, emits them, then flushes episode data."""
        self.update_episode_data(logger_args=logger_args, model=model)
        self.telemeter.emit(
            EpisodeStatsTelemetry(
                stats=self.data,
                mode=model.experiment_mode,
                episode=logger_args[f"{model.experiment_mode}_episodes"],
                step=model.episode_steps,
                emitter=self,
            )
        )
        self._flush()

    def _flush(self):
        """Resets accumulated episode data."""
        self.data = self._blank_data()
        self.received_lm_events = {}
        self.lm_id_to_name_dict = {}


class MontyHandlerTelemetryConnector(TelemetrySubscriber):
    """Receives episode stats and forwards them to Monty handlers."""

    @property
    def logger_names(self) -> list[str]:
        """Names of loggers to subscribe to."""
        return [
            f"telemetry.{EpisodeTelemetryHandler.__module__}",
        ]

    def __init__(self, handlers: Sequence[MontyHandler], output_dir: Path, **kwargs):
        """Initializes the subscriber with handlers and output parameters.

        Args:
            handlers: `MontyHandler` instances that receive episode reports via
                ``handler.report_episode()``. Replaces the handler list previously owned
                by `BasicGraphMatchingLogger`.
            output_dir: Output path forwarded to handlers.
            **kwargs: Forwarded to superclass.
        """
        super().__init__(**kwargs)
        self.handlers = handlers
        self.output_dir = output_dir

    def _consume(self, schema: TelemetrySchema):
        """Processes a single episode stats event."""
        if isinstance(schema, EpisodeStatsTelemetry):
            self._log_episode(schema)

    def _log_episode(self, event: EpisodeStatsTelemetry):
        """Forwards the episode stats to all handlers.

        Mirrors `BasicGraphMatchingLogger.log_episode`.
        """
        for handler in self.handlers:
            handler.report_episode(
                event.stats, self.output_dir, event.episode, event.mode
            )
