# @package experiment.config

defaults:
  - clear

monty_config:
  motor_system_config:
    motor_system_args:
      policy:
        use_goal_state_driven_actions: false
        agent_id: ${monty.agent_id:agent_id_0}
        action_sampler:
          actions:
          - ${monty.class:tbp.monty.frameworks.actions.actions.LookUp}
          - ${monty.class:tbp.monty.frameworks.actions.actions.LookDown}
          - ${monty.class:tbp.monty.frameworks.actions.actions.TurnLeft}
          - ${monty.class:tbp.monty.frameworks.actions.actions.TurnRight}
          _target_: tbp.monty.frameworks.actions.action_samplers.ConstantSampler
          rotation_degrees: 5.0
        _target_: tbp.monty.frameworks.models.motor_policies.InformedPolicy
    motor_system_class: ${monty.class:tbp.monty.frameworks.models.motor_system.MotorSystem}
  monty_args:
    num_exploratory_steps: 1000
    min_eval_steps: 3
    min_train_steps: 3
    max_total_steps: 2500
  monty_class: ${monty.class:tbp.monty.frameworks.models.graph_matching.MontyForGraphMatching}
  learning_module_configs:
    learning_module_0:
      learning_module_class: ${monty.class:tbp.monty.frameworks.models.displacement_matching.DisplacementGraphLM}
      learning_module_args:
        k: 5
        match_attribute: displacement
  sensor_module_configs:
    sensor_module_0:
      sensor_module_class: ${monty.class:tbp.monty.frameworks.models.sensor_modules.CameraSM}
      sensor_module_args:
        sensor_module_id: patch
        features:
        - pose_vectors
        - pose_fully_defined
        - on_object
        - object_coverage
        - rgba
        - hsv
        - principal_curvatures
        - principal_curvatures_log
        - gaussian_curvature
        - mean_curvature
        - gaussian_curvature_sc
        - mean_curvature_sc
        save_raw_obs: true
    sensor_module_1:
      sensor_module_class: ${monty.class:tbp.monty.frameworks.models.sensor_modules.Probe}
      sensor_module_args:
        sensor_module_id: view_finder
        save_raw_obs: true
  sm_to_agent_dict:
    patch: ${monty.agent_id:agent_id_0}
    view_finder: ${monty.agent_id:agent_id_0}
  sm_to_lm_matrix:
  - - 0
  lm_to_lm_matrix: null
  lm_to_lm_vote_matrix: null
