# @package experiment.config.monty_config.learning_modules

defaults:
  - hypotheses_updater/burst_sampling_10nn@learning_module_0

learning_module_0:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  max_match_distance: 0.01
  tolerances:
    patch:
      hsv: ${np.array:[0.1, 1, 1]}
      principal_curvatures_log: ${np.ones:2}
  feature_weights: {}
  max_graph_size: 0.4
  num_model_voxels_per_dim: 200
  gsg: null
