name: Check Assignees Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  check-assignees-approval:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    steps:
      - name: All assignees approve?
        uses: actions/github-script@v7
        with:
          script: |
            // Hard code the maintainers list for now
            // TODO: see if we can pull this from the maintainers file
            const maintainers = [
              "vkakerbeck",
              "nielsleadholm",
              "tristanls",
              "codeallthethingz",
              "scottcanoe",
              "hlee9212",
              "ramyamounir",
            ];
            
            const pull_number = context.payload.pull_request.number;
            const { owner, repo } = context.repo;
            
            console.log(`Checking approvals for PR #${pull_number}`);
            
            const { data: pr } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number,
            });
            
            const assignees = pr.assignees.map(a => a.login);
            // Check for no maintainers
            if (assignees.length === 0) {
              core.setFailed("No assignees listed.");
              return;
            }
            
            // Check for non maintainers
            const nonMaintainers = assignees.filter(assignee =>
              !maintainers.includes(assignee)
            );
            if (nonMaintainers.length !== 0) {
              core.setFailed(`Non maintainers in assignee list: ${nonMaintainers.join(", ")}`);
              return;
            }
            
            // Check that last review was an approval
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner,
              repo,
              pull_number,
            });
            const latestReviews = {};
            for (const review of reviews) {
              latestReviews[review.user.login] = review.state;
            }
            
            console.log("Latest review states: ", latestReviews);
            
            const notApproved = assignees.filter(assignee => 
              latestReviews[assignee] !== 'APPROVED'
            );
            
            if (notApproved.length > 0) {
              core.setFailed(`The following assignees have not approved: ${notApproved.join(", ")}`);
            } else {
              console.log("All assignees have approved the pull request.");
            }
