name: Check Assignees Approval

on:
  pull_request_review:
    types: [submitted]

jobs:
  check_assignees_approval:
    name: check-assignees-approval
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    steps:
      - name: All assignees approve?
        uses: actions/github-script@v7
        with:
          script: |
            // Hard code the maintainers list for now
            // TODO: see if we can pull this from the maintainers file
            const maintainers = [
              "vkakerbeck",
              "nielsleadholm",
              "tristanls",
              "codeallthethingz",
              "scottcanoe",
              "hlee9212",
              "ramyamounir",
            ];
            
            const pull_number = context.payload.pull_request.number;
            const { owner, repo } = context.repo;
            
            console.log(`Checking approvals for PR #${pull_number}`);
            
            const { data: pr } = await github.rest.pulls.get({
              owner,
              repo,
              pull_number,
            });
            const assignees = pr.assignees.map(a => a.login);
            
            // Check for no maintainers
            if (assignees.length === 0) {
              core.setFailed("No assignees listed.");
              return;
            }
            
            // Check for non maintainers
            const nonMaintainers = assignees.filter(assignee =>
              !maintainers.includes(assignee)
            );
            if (nonMaintainers.length !== 0) {
              core.setFailed(`Non-maintainers in assignee list: ${nonMaintainers.join(", ")}`);
              return;
            }
            
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner,
              repo,
              pull_number,
            });

            // Collect the latest review states only for reviewers on the maintainer list
            const latestReviews = reviews
              .filter(r => maintainers.includes(r.user.login))
              .reduce((result, review) => {
                result[review.user.login] = review.state;
                return result;
              }, {});
            
            console.log("Latest assignee review states: ", latestReviews);
            
            const notApproved = assignees.filter(assignee => 
              latestReviews[assignee] !== 'APPROVED'
            );
            
            if (notApproved.length > 0) {
              core.setFailed(`The following assignees have not approved: ${notApproved.join(", ")}\n` +
                             "Note: the latest review for each assignee must be an approval.");
            } else {
              console.log(`All assignees have approved: ${assignees.join(", ")}`);
            }
