name: Monty API Docs

concurrency:
  group: pages
  cancel-in-progress: false

on:
  workflow_run:
    workflows:
      - Monty
    branches:
      - main
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  deploy_sphinx_monty_api_docs:
    name: deploy-sphinx-monty-api-docs
    runs-on: ubuntu-latest
    if: ${{ (github.repository_owner == 'thousandbrainsproject') && (github.event.workflow_run.conclusion == 'success') }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout tbp.monty
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          path: tbp.monty
      - name: Filter by path for a push
        id: filter_by_path_push
        working-directory: tbp.monty
        run: |
          git diff --name-only HEAD^1 > changed_files.txt
          while IFS= read -r changed_file
          do
            echo $changed_file
            if [[ $changed_file != .github/ISSUE_TEMPLATE/* ]] &&
               [[ $changed_file != .vscode/* ]] &&
               [[ $changed_file != docs/* ]] &&
               [[ $changed_file != rfcs/* ]] &&
               [[ $changed_file != tools/* ]] &&
               [[ $changed_file != CODE_OF_CONDUCT.md ]] &&
               [[ $changed_file != CONTRIBUTING.md ]] &&
               [[ $changed_file != LICENSE ]] &&
               [[ $changed_file != MAINTAINERS.md ]] &&
               [[ $changed_file != README.md ]]; then
              echo "should_run_monty_api_docs=true" >> $GITHUB_OUTPUT
              exit 0
            fi
          done < changed_files.txt
      - name: Deploy Monty API docs
        id: deployment
        if: ${{ steps.filter_by_path_push.outputs.should_run_monty_api_docs == 'true'}}
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-${{ github.sha }}