name: Monty API Docs

concurrency:
  group: pages
  cancel-in-progress: false

on:
  workflow_run:
    workflows:
      - Monty
    branches:
      - main
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  deploy_sphinx_monty_api_docs:
    name: deploy-sphinx-monty-api-docs
    runs-on: ubuntu-latest
    if: ${{ (github.repository_owner == 'thousandbrainsproject') && (github.event.workflow_run.conclusion == 'success') }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout tbp.monty
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          path: tbp.monty
      # Downloading the artifact from the previous run so that actions/deploy-pages can find it.
      # If the artifact is not found, then there is nothing to deploy and the last step
      # will succeed, indicating job success.
      - name: Download artifact
        id: download
        uses: actions/download-artifact@v4
        with:
          name: github-pages-${{ github.sha }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: github-pages-${{ github.sha }}
          path: github-pages-${{ github.sha }}
      - name: Deploy Monty API docs
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-${{ github.sha }}
      - name: Ignore download failure
        if: ${{ failure() }}
        run: |
          if [ '${{ steps.download.conclusion }}' == 'failure' ]
          then
            exit 0
          fi
          exit 1
